// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: advice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_CREATE Operation = 0
	Operation_UPDATE Operation = 1
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
	}
	Operation_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_advice_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_advice_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_advice_proto_rawDescGZIP(), []int{0}
}

type GetUserAdviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAdviceRequest) Reset() {
	*x = GetUserAdviceRequest{}
	mi := &file_advice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAdviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAdviceRequest) ProtoMessage() {}

func (x *GetUserAdviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAdviceRequest.ProtoReflect.Descriptor instead.
func (*GetUserAdviceRequest) Descriptor() ([]byte, []int) {
	return file_advice_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserAdviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAdviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advice        string                 `protobuf:"bytes,1,opt,name=advice,proto3" json:"advice,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAdviceResponse) Reset() {
	*x = GetUserAdviceResponse{}
	mi := &file_advice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAdviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAdviceResponse) ProtoMessage() {}

func (x *GetUserAdviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAdviceResponse.ProtoReflect.Descriptor instead.
func (*GetUserAdviceResponse) Descriptor() ([]byte, []int) {
	return file_advice_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserAdviceResponse) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

func (x *GetUserAdviceResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateUpdateAdviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=pb.Operation" json:"operation,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Advice        string                 `protobuf:"bytes,3,opt,name=advice,proto3" json:"advice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUpdateAdviceRequest) Reset() {
	*x = CreateUpdateAdviceRequest{}
	mi := &file_advice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUpdateAdviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpdateAdviceRequest) ProtoMessage() {}

func (x *CreateUpdateAdviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpdateAdviceRequest.ProtoReflect.Descriptor instead.
func (*CreateUpdateAdviceRequest) Descriptor() ([]byte, []int) {
	return file_advice_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUpdateAdviceRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_CREATE
}

func (x *CreateUpdateAdviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUpdateAdviceRequest) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

type CreateUpdateAdviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUpdateAdviceResponse) Reset() {
	*x = CreateUpdateAdviceResponse{}
	mi := &file_advice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUpdateAdviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpdateAdviceResponse) ProtoMessage() {}

func (x *CreateUpdateAdviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpdateAdviceResponse.ProtoReflect.Descriptor instead.
func (*CreateUpdateAdviceResponse) Descriptor() ([]byte, []int) {
	return file_advice_proto_rawDescGZIP(), []int{3}
}

var File_advice_proto protoreflect.FileDescriptor

const file_advice_proto_rawDesc = "" +
	"\n" +
	"\fadvice.proto\x12\x02pb\x1a\x0ftimestamp.proto\"/\n" +
	"\x14GetUserAdviceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"j\n" +
	"\x15GetUserAdviceResponse\x12\x16\n" +
	"\x06advice\x18\x01 \x01(\tR\x06advice\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"y\n" +
	"\x19CreateUpdateAdviceRequest\x12+\n" +
	"\toperation\x18\x01 \x01(\x0e2\r.pb.OperationR\toperation\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06advice\x18\x03 \x01(\tR\x06advice\"\x1c\n" +
	"\x1aCreateUpdateAdviceResponse*#\n" +
	"\tOperation\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x012\xaa\x01\n" +
	"\rAdviceService\x12B\n" +
	"\tGetAdvice\x12\x18.pb.GetUserAdviceRequest\x1a\x19.pb.GetUserAdviceResponse\"\x00\x12U\n" +
	"\x12CreateUpdateAdvice\x12\x1d.pb.CreateUpdateAdviceRequest\x1a\x1e.pb.CreateUpdateAdviceResponse\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_advice_proto_rawDescOnce sync.Once
	file_advice_proto_rawDescData []byte
)

func file_advice_proto_rawDescGZIP() []byte {
	file_advice_proto_rawDescOnce.Do(func() {
		file_advice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advice_proto_rawDesc), len(file_advice_proto_rawDesc)))
	})
	return file_advice_proto_rawDescData
}

var file_advice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_advice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_advice_proto_goTypes = []any{
	(Operation)(0),                     // 0: pb.Operation
	(*GetUserAdviceRequest)(nil),       // 1: pb.GetUserAdviceRequest
	(*GetUserAdviceResponse)(nil),      // 2: pb.GetUserAdviceResponse
	(*CreateUpdateAdviceRequest)(nil),  // 3: pb.CreateUpdateAdviceRequest
	(*CreateUpdateAdviceResponse)(nil), // 4: pb.CreateUpdateAdviceResponse
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_advice_proto_depIdxs = []int32{
	5, // 0: pb.GetUserAdviceResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: pb.CreateUpdateAdviceRequest.operation:type_name -> pb.Operation
	1, // 2: pb.AdviceService.GetAdvice:input_type -> pb.GetUserAdviceRequest
	3, // 3: pb.AdviceService.CreateUpdateAdvice:input_type -> pb.CreateUpdateAdviceRequest
	2, // 4: pb.AdviceService.GetAdvice:output_type -> pb.GetUserAdviceResponse
	4, // 5: pb.AdviceService.CreateUpdateAdvice:output_type -> pb.CreateUpdateAdviceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_advice_proto_init() }
func file_advice_proto_init() {
	if File_advice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advice_proto_rawDesc), len(file_advice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_advice_proto_goTypes,
		DependencyIndexes: file_advice_proto_depIdxs,
		EnumInfos:         file_advice_proto_enumTypes,
		MessageInfos:      file_advice_proto_msgTypes,
	}.Build()
	File_advice_proto = out.File
	file_advice_proto_goTypes = nil
	file_advice_proto_depIdxs = nil
}
